name: post-tag-release
run-name: ${{ github.actor }} is running post tag release
on:
  push:
    tags:
      - '*'

concurrency:
  group: tag-group

jobs:
    build-n-test:
        runs-on: ubuntu-latest
        name: qa
        permissions:
          id-token: write
        steps:
            - name: "fetch code"
              uses: actions/checkout@v6
            - uses: actions/setup-go@v6
              with:
                check-latest: true
                cache-dependency-path: |
                  backend/go.sum
            - name: "Run test"
              uses: ./.github/actions/go-test
