name: quality-control
run-name: ${{ github.actor }} is running QA
on:
  push:
    branches-ignore: [ main, auto-update-changelog ]

concurrency:
  group: qa-group
  cancel-in-progress: true

env:
  VERBOSITY_LEVEL: ${{ vars.VERBOSITY_LEVEL }}

jobs:
    build-n-test:
        runs-on: ubuntu-latest
        name: qa
        permissions:
          id-token: write
        steps:
            - name: "fetch code"
              uses: actions/checkout@v6
            - uses: actions/setup-go@v6
              with:
                check-latest: true
                cache-dependency-path: |
                  go.sum
            - name: "Run test"
              uses: ./.github/actions/go-test
